// products-data.js
// ประกาศกลุ่มทักษะตามตารางและผลรวมจำนวนสินค้าจริงจากไฟล์ Excel ทั้งหมด
export const CATEGORIES = [
  { slug: 'reading', name: 'อ่าน-เขียน พัฒนาภาษา', count: 121, color: '#d85443' },
  { slug: 'math', name: 'คณิตศาสตร์', count: 25, color: '#f0c93e' },
  { slug: 'stem', name: 'วิทยาศาสตร์ STEM/STEAM & CT/CS', count: 15, color: '#58bccb' },
  { slug: 'life', name: 'ทักษะชีวิตและความรู้ทั่วไป', count: 20, color: '#7758ad' },
];

export function getCategory(slug) {
  return CATEGORIES.find(c => c.slug === slug);
}

// ข้อมูลรายการสินค้าจริงทั้งหมดที่แปลงมาจากไฟล์ Excel (จำนวน 181 รายการ)
export const ALL_PRODUCTS = [
  { id: 'reading-1', code: '9770009', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 1`, subject: 'ภาษาต่างประเทศ', level: 'ป.1-3' },
  { id: 'reading-2', code: '9770010', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 2`, subject: 'ภาษาต่างประเทศ', level: 'ป.1-3' },
  { id: 'reading-3', code: '9770011', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 3`, subject: 'ภาษาต่างประเทศ', level: 'ป.1-3' },
  { id: 'reading-4', code: '9770012', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 4`, subject: 'ภาษาต่างประเทศ', level: 'ป.1' },
  { id: 'reading-5', code: '9770013', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 5`, subject: 'ภาษาต่างประเทศ', level: 'ป.1' },
  { id: 'reading-6', code: '9770014', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาจีน  เล่ม 6`, subject: 'ภาษาต่างประเทศ', level: 'ป.1' },
  { id: 'reading-7', code: '9771004', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 1 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.5' },
  { id: 'reading-8', code: '9771005', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 1 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.5' },
  { id: 'reading-9', code: '9771006', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 1 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.5' },
  { id: 'reading-10', code: '9771007', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 1 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.5' },
  { id: 'reading-11', code: '9771008', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 2 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.6' },
  { id: 'reading-12', code: '9771009', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 2 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.6' },
  { id: 'reading-13', code: '9771010', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 2 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.6' },
  { id: 'reading-14', code: '9771011', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 2 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.6' },
  { id: 'reading-15', code: '9771012', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 3 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.1' },
  { id: 'reading-16', code: '9771013', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 3 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.1' },
  { id: 'reading-17', code: '9771014', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 3 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.1' },
  { id: 'reading-18', code: '9771015', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 3 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.1' },
  { id: 'reading-19', code: '9771016', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 4 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.2' },
  { id: 'reading-20', code: '9771017', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 4 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.2' },
  { id: 'reading-21', code: '9771018', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 4 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.2' },
  { id: 'reading-22', code: '9771019', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 4 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.2' },
  { id: 'reading-23', code: '9771020', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 5 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.3' },
  { id: 'reading-24', code: '9771021', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 5 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.3' },
  { id: 'reading-25', code: '9771022', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 5 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.3' },
  { id: 'reading-26', code: '9771023', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 5 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.3' },
  { id: 'reading-27', code: '9771024', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 6 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.4' },
  { id: 'reading-28', code: '9771025', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำพื้นฐาน 6 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.4' },
  { id: 'reading-29', code: '9771026', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 6 เล่ม 1`, subject: 'ภาษาไทย', level: 'ป.4' },
  { id: 'reading-30', code: '9771027', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาไทย คำยาก 6 เล่ม 2`, subject: 'ภาษาไทย', level: 'ป.4' },
  { id: 'reading-31', code: '9771028', name: `(online) คลังคำศัพท์ปฐมวัย`, subject: 'ภาษาไทย', level: 'ปฐมวัย' },
  { id: 'reading-32', code: '9771029', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 1`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-33', code: '9771030', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 2`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-34', code: '9771031', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 3`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-35', code: '9771032', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 4`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-36', code: '9771033', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 5`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-37', code: '9771034', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 6`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-38', code: '9771035', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 7`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-39', code: '9771036', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 8`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-40', code: '9771037', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 9`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-41', code: '9771038', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 10`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-42', code: '9771039', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 11`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-43', code: '9771040', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 12`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-44', code: '9771041', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 13`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-45', code: '9771042', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 14`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-46', code: '9771043', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 15`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-47', code: '9771044', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 16`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-48', code: '9771045', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 17`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-49', code: '9771046', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 18`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-50', code: '9771047', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 19`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-51', code: '9771048', name: `(online) สื่อฝึกทักษะการอ่านออกเขียนได้ ชุดที่ 20`, subject: 'ภาษาไทย', level: 'ป.1-6' },
  { id: 'reading-52', code: '9772007', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 1`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-53', code: '9772008', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 2`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-54', code: '9772009', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 3`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-55', code: '9772010', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 4`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-56', code: '9772011', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 5`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-57', code: '9772012', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 6`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-58', code: '9772013', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 7`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-59', code: '9772014', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 8`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-60', code: '9772015', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 9`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-61', code: '9772016', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 10`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-62', code: '9772017', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 11`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-63', code: '9772018', name: `(online) นิทานปฐมวัย ภาษาอังกฤษ Phonics เล่ม 12`, subject: 'ภาษาอังกฤษ', level: 'อนุบาล' },
  { id: 'reading-64', code: '9772031', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 1`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-65', code: '9772032', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 2`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-66', code: '9772033', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 3`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-67', code: '9772034', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 4`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-68', code: '9772035', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 5`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-69', code: '9772036', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 6`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-70', code: '9772037', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 7`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-71', code: '9772038', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 8`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-72', code: '9772039', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 9`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-73', code: '9772040', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 10`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-74', code: '9772041', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 11`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-75', code: '9772042', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 12`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-76', code: '9772043', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 13`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-77', code: '9772044', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 14`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-78', code: '9772045', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 15`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-79', code: '9772046', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 16`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-80', code: '9772047', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 17`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-81', code: '9772048', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 18`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-82', code: '9772049', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 19`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-83', code: '9772050', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 20`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-84', code: '9772051', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 21`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-85', code: '9772052', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 22`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-86', code: '9772053', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 23`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-87', code: '9772054', name: `(online) แบบฝึกคำศัพท์ต้องรู้ ภาษาอังกฤษ Phonics เล่ม 24`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-88', code: '9772055', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 1`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-89', code: '9772056', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 2`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-90', code: '9772057', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 3`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-91', code: '9772058', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 4`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-92', code: '9772059', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 5`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-93', code: '9772060', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 6`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-94', code: '9772061', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 7`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-95', code: '9772062', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 8`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-96', code: '9772063', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 9`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-97', code: '9772064', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 10`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-98', code: '9772065', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 11`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-99', code: '9772066', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 12`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-100', code: '9772067', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 13`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-101', code: '9772068', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 14`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-102', code: '9772069', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 15`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-103', code: '9772070', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 16`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-104', code: '9772071', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 17`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-105', code: '9772072', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 18`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-106', code: '9772073', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 19`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-107', code: '9772074', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 20`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-108', code: '9772075', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 21`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-109', code: '9772076', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 22`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-110', code: '9772077', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 23`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-111', code: '9772078', name: `(online) นิทานระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 24`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-112', code: '9772079', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 1`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-113', code: '9772080', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 2`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-114', code: '9772081', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 3`, subject: 'ภาษาอังกฤษ', level: 'ป.1-3' },
  { id: 'reading-115', code: '9772082', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 4`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-116', code: '9772083', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 5`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-117', code: '9772084', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา ภาษาอังกฤษ Phonics เล่ม 6`, subject: 'ภาษาอังกฤษ', level: 'ป.4-6' },
  { id: 'reading-118', code: '9772085', name: `(online) คลังคำศัพท์ระดับชั้นมัธยมศึกษา ภาษาอังกฤษ Phonics เล่ม 1`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-119', code: '9772086', name: `(online) คลังคำศัพท์ระดับชั้นมัธยมศึกษา ภาษาอังกฤษ Phonics เล่ม 2`, subject: 'ภาษาอังกฤษ', level: 'ม.1-3' },
  { id: 'reading-120', code: '9772087', name: `(online) คลังคำศัพท์ระดับชั้นมัธยมศึกษา ภาษาอังกฤษ Phonics เล่ม 3`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'reading-121', code: '9772088', name: `(online) คลังคำศัพท์ระดับชั้นมัธยมศึกษา ภาษาอังกฤษ Phonics เล่ม 4`, subject: 'ภาษาอังกฤษ', level: 'ม.4-6' },
  { id: 'math-122', code: '9773001', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 1`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-123', code: '9773002', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 2`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-124', code: '9773003', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 3`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-125', code: '9773004', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 4`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-126', code: '9773005', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 5`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-127', code: '9773006', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 6`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-128', code: '9773007', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 7`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-129', code: '9773008', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 8`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-130', code: '9773009', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 9`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-131', code: '9773010', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 10`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-132', code: '9773011', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 11`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-133', code: '9773012', name: `(online) นิทานปฐมวัย คณิตศาสตร์ เล่ม 12`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'math-134', code: '9773013', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 1`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-135', code: '9773014', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 2`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-136', code: '9773015', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 3`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-137', code: '9773016', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 4`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-138', code: '9773017', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 5`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-139', code: '9773018', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 6`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-140', code: '9773019', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 7`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-141', code: '9773020', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 8`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-142', code: '9773021', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 9`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-143', code: '9773022', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 10`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-144', code: '9773023', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 11`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-145', code: '9773024', name: `(online) แบบฝึกคำศัพท์ต้องรู้ คณิตศาสตร์ เล่ม 12`, subject: 'คณิตศาสตร์', level: 'ป.1-3' },
  { id: 'math-146', code: '9773025', name: `(online) คลังคำศัพท์ปฐมวัย คณิตศาสตร์`, subject: 'คณิตศาสตร์', level: 'อนุบาล' },
  { id: 'stem-147', code: '9774001', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 1`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-148', code: '9774002', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 2`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-149', code: '9774003', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 3`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-150', code: '9774004', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 4`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-151', code: '9774005', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 5`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-152', code: '9774006', name: `(online) นิทานปฐมวัย วิทยาศาสตร์ เล่ม 6`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-153', code: '9774019', name: `(online) สื่อการสอนวิทยาศาสตร์เสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 1`, subject: 'วิทยาศาสตร์', level: 'ป.1' },
  { id: 'stem-154', code: '9774020', name: `(online) สื่อการสอนวิทยาศาสตร์เสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 2`, subject: 'วิทยาศาสตร์', level: 'ป.2' },
  { id: 'stem-155', code: '9774021', name: `(online) สื่อการสอนวิทยาศาสตร์เสมือนจริง (3D/AR) ระดับชั้นมัธยมศึกษา ชุดที่ 1`, subject: 'วิทยาศาสตร์', level: 'ม.1' },
  { id: 'stem-156', code: '9774022', name: `(online) สื่อการสอนวิทยาศาสตร์เสมือนจริง (3D/AR) ระดับชั้นมัธยมศึกษา ชุดที่ 2`, subject: 'วิทยาศาสตร์', level: 'ม.2' },
  { id: 'stem-157', code: '9774023', name: `(online) สื่อการสอนวิทยาศาสตร์เสมือนจริง (3D/AR) ระดับชั้นมัธยมศึกษา ชุดที่ 3`, subject: 'วิทยาศาสตร์', level: 'ม.3' },
  { id: 'stem-158', code: '9774024', name: `(online) คลังคำศัพท์ปฐมวัย วิทยาศาสตร์`, subject: 'วิทยาศาสตร์', level: 'อนุบาล' },
  { id: 'stem-159', code: '9774025', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา วิทยาศาสตร์ ชุดที่ 1`, subject: 'วิทยาศาสตร์', level: 'ป.1-6' },
  { id: 'stem-160', code: '9774026', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา วิทยาศาสตร์ ชุดที่ 2`, subject: 'วิทยาศาสตร์', level: 'ป.1-6' },
  { id: 'stem-161', code: '9774027', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา วิทยาศาสตร์ ชุดที่ 3`, subject: 'วิทยาศาสตร์', level: 'ป.1-6' },
  { id: 'life-162', code: '9775001', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 1`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-163', code: '9775002', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 2`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-164', code: '9775003', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 3`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-165', code: '9775004', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 4`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-166', code: '9775005', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 5`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-167', code: '9775006', name: `(online) นิทานปฐมวัย บูรณาการ เล่ม 6`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-168', code: '9775019', name: `(online) สื่อการสอนสังคมศึกษาเสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 1`, subject: 'สังคม', level: 'ป.1' },
  { id: 'life-169', code: '9775020', name: `(online) สื่อการสอนสังคมศึกษาเสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 2`, subject: 'สังคม', level: 'ป.2' },
  { id: 'life-170', code: '9775021', name: `(online) สื่อการสอนสังคมศึกษาเสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 3`, subject: 'สังคม', level: 'ป.3' },
  { id: 'life-171', code: '9775022', name: `(online) สื่อการสอนสังคมศึกษาเสมือนจริง (3D/AR) ระดับชั้นประถมศึกษา ชุดที่ 4`, subject: 'สังคม', level: 'ป.4' },
  { id: 'life-172', code: '9775023', name: `(online) คลังคำศัพท์ปฐมวัย บูรณาการ`, subject: 'บูรณาการ', level: 'อนุบาล' },
  { id: 'life-173', code: '9775024', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 1`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-174', code: '9775025', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 2`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-175', code: '9775026', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 3`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-176', code: '9775027', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 4`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-177', code: '9775028', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 5`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-178', code: '9775029', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 6`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-179', code: '9775030', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 7`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-180', code: '9775031', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 8`, subject: 'สังคม', level: 'ป.1-3' },
  { id: 'life-181', code: '9775032', name: `(online) คลังคำศัพท์ระดับชั้นประถมศึกษา สังคมศึกษา ชุดที่ 9`, subject: 'สังคม', level: 'ป.1-3' },
];

export function generateProducts(slug) {
  if (slug === 'all') return ALL_PRODUCTS;
  return ALL_PRODUCTS.filter(p => p.id.startsWith(slug));
}